"""restrincion en Comment

Revision ID: 64fba70ad630
Revises: 36e61b7bde33
Create Date: 2025-03-21 09:58:02.681533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fba70ad630'
down_revision: Union[str, None] = '36e61b7bde33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_post', 'comments', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_post', 'comments', type_='unique')
    # ### end Alembic commands ###
